AllCops:
  TargetRubyVersion: 3.4
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "test/fixtures/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 80
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Max: 60
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Max: 200
  Exclude:
    - "test/**/*"

Metrics/ModuleLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 17

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "Rakefile"

Naming/VariableNumber:
  Exclude:
    - "test/**/*"

Style/FormatStringToken:
  Exclude:
    - "test/**/*"

Layout/LineLength:
  Max: 150
